import type { InstitutionalCalendarEvent } from '@/lib/types';

export const institutionalCalendarEvents: InstitutionalCalendarEvent[] = [
  {
    id: 'evt-001',
    title: 'Mid-Term Assessment Week',
    type: 'exam',
    level: 'secondary',
    centreName: 'SMA MAIWP Kuala Lumpur',
    startDate: '2026-03-09',
    endDate: '2026-03-13',
    owner: 'Academic Unit',
    status: 'upcoming',
  },
  {
    id: 'evt-002',
    title: 'Inter-Centre Sports Carnival',
    type: 'co_curricular',
    level: 'primary',
    centreName: 'SABK Darul Ulum',
    startDate: '2026-04-18',
    endDate: '2026-04-18',
    owner: 'Co-curricular Unit',
    status: 'upcoming',
  },
  {
    id: 'evt-003',
    title: 'Ramadan Break',
    type: 'holiday',
    level: 'maiwp',
    centreName: 'All Centres',
    startDate: '2026-03-20',
    endDate: '2026-03-27',
    owner: 'HQ Admin',
    status: 'upcoming',
  },
  {
    id: 'evt-004',
    title: 'Quarterly Safety Inspection',
    type: 'inspection',
    level: 'preschool',
    centreName: 'Tadika Islam MAIWP Cheras',
    startDate: '2026-02-27',
    endDate: '2026-02-27',
    owner: 'Compliance Unit',
    status: 'upcoming',
  },
  {
    id: 'evt-005',
    title: 'Tahfiz Intensive Workshop',
    type: 'academic',
    level: 'secondary',
    centreName: 'SMISTA',
    startDate: '2026-02-20',
    endDate: '2026-02-24',
    owner: 'Academic Unit',
    status: 'ongoing',
  },
];
