import type { CoCurricularActivity, CoCurricularParticipation } from '@/lib/types';

export const cocurricularActivities: CoCurricularActivity[] = [
  {
    id: 'cca-001',
    code: 'CCA-TKD-01',
    name: 'Taekwondo Club',
    type: 'sports',
    centreName: 'SMA MAIWP Kuala Lumpur',
    coach: 'Ust. Hakim Rahman',
    schedule: 'Tuesday, 3:30 PM - 5:00 PM',
    maxParticipants: 40,
    activeParticipants: 34,
    status: 'active',
  },
  {
    id: 'cca-002',
    code: 'CCA-NASYID-01',
    name: 'Nasyid Ensemble',
    type: 'arts',
    centreName: 'SABK Darul Ulum',
    coach: 'Pn. Norliza Ahmad',
    schedule: 'Wednesday, 2:30 PM - 4:00 PM',
    maxParticipants: 25,
    activeParticipants: 22,
    status: 'active',
  },
  {
    id: 'cca-003',
    code: 'CCA-BRIG-01',
    name: 'Briged Amal',
    type: 'uniformed',
    centreName: 'SMISTA',
    coach: 'Ust. Khairul Anwar',
    schedule: 'Friday, 8:00 AM - 10:00 AM',
    maxParticipants: 50,
    activeParticipants: 46,
    status: 'active',
  },
  {
    id: 'cca-004',
    code: 'CCA-QIRAAT-01',
    name: 'Qiraat & Tilawah Circle',
    type: 'religious',
    centreName: 'Kolej Profesional MAIWP',
    coach: 'Dr. Aizuddin Aziz',
    schedule: 'Monday, 5:00 PM - 6:30 PM',
    maxParticipants: 30,
    activeParticipants: 18,
    status: 'planned',
  },
];

export const cocurricularParticipation: CoCurricularParticipation[] = [
  {
    id: 'ccp-001',
    studentId: '1',
    studentName: 'Ahmad Bin Abdullah',
    activityId: 'cca-001',
    activityName: 'Taekwondo Club',
    attendanceRate: 92,
    meritPoints: 12,
    achievement: 'Bronze - District Sparring 2025',
    status: 'active',
  },
  {
    id: 'ccp-002',
    studentId: '2',
    studentName: 'Fatimah Binti Ismail',
    activityId: 'cca-002',
    activityName: 'Nasyid Ensemble',
    attendanceRate: 96,
    meritPoints: 15,
    achievement: 'Best Vocalist - School Festival',
    status: 'active',
  },
  {
    id: 'ccp-003',
    studentId: '3',
    studentName: 'Nurul Aisyah binti Abdullah',
    activityId: 'cca-003',
    activityName: 'Briged Amal',
    attendanceRate: 88,
    meritPoints: 9,
    status: 'active',
  },
  {
    id: 'ccp-004',
    studentId: '4',
    studentName: 'Muhammad Irfan bin Abdullah',
    activityId: 'cca-004',
    activityName: 'Qiraat & Tilawah Circle',
    attendanceRate: 80,
    meritPoints: 6,
    status: 'on_hold',
  },
];
