import type { ComplaintRecord, ComplaintTimelineEntry } from '@/lib/types';

export const complaintRecords: ComplaintRecord[] = [
  {
    id: 'cmp-001',
    referenceNo: 'CMP-2026-0001',
    studentId: '1',
    studentName: 'Ahmad Bin Abdullah',
    centreName: 'Pusat Jagaan Wangsa Maju',
    category: 'billing',
    subject: 'Invoice subsidy mismatch',
    description: 'Guardian reported subsidy percentage mismatch for January invoice.',
    submittedBy: 'Abdullah Bin Hassan',
    channel: 'portal',
    status: 'investigating',
    priority: 'high',
    assignedTo: 'Finance Officer (AR)',
    submittedAt: new Date('2026-02-12T10:22:00'),
    dueAt: new Date('2026-02-25T17:00:00'),
  },
  {
    id: 'cmp-002',
    referenceNo: 'CMP-2026-0002',
    studentId: '2',
    studentName: 'Fatimah Binti Ismail',
    centreName: 'Pusat Jagaan Wangsa Maju',
    category: 'attendance',
    subject: 'Face ID check-in missing',
    description: 'Attendance for 10 Feb not reflected despite check-in at gate terminal.',
    submittedBy: 'Ismail Bin Ahmad',
    channel: 'whatsapp',
    status: 'resolved',
    priority: 'medium',
    assignedTo: 'Centre Admin',
    submittedAt: new Date('2026-02-11T08:10:00'),
    dueAt: new Date('2026-02-18T17:00:00'),
    resolvedAt: new Date('2026-02-13T14:30:00'),
  },
  {
    id: 'cmp-003',
    referenceNo: 'CMP-2026-0003',
    studentId: '3',
    studentName: 'Nurul Aisyah binti Abdullah',
    centreName: 'SMA MAIWP Kuala Lumpur',
    category: 'facility',
    subject: 'Hostel water disruption',
    description: 'Water interruption in hostel block B reported by guardian.',
    submittedBy: 'Abdullah Bin Hassan',
    channel: 'email',
    status: 'new',
    priority: 'critical',
    assignedTo: 'Facilities Unit',
    submittedAt: new Date('2026-02-21T19:05:00'),
    dueAt: new Date('2026-02-24T12:00:00'),
  },
  {
    id: 'cmp-004',
    referenceNo: 'CMP-2026-0004',
    studentId: '4',
    studentName: 'Muhammad Irfan bin Abdullah',
    centreName: 'Kolej Profesional MAIWP',
    category: 'staff',
    subject: 'Advisory response delay',
    description: 'No response from advisor for timetable clash request for 2 weeks.',
    submittedBy: 'Muhammad Irfan bin Abdullah',
    channel: 'portal',
    status: 'closed',
    priority: 'low',
    assignedTo: 'Academic Office',
    submittedAt: new Date('2026-01-28T09:15:00'),
    dueAt: new Date('2026-02-05T17:00:00'),
    resolvedAt: new Date('2026-02-03T15:20:00'),
  },
];

export const complaintTimeline: ComplaintTimelineEntry[] = [
  {
    id: 'cmp-001-t1',
    complaintId: 'cmp-001',
    action: 'Complaint Submitted',
    actor: 'Abdullah Bin Hassan',
    note: 'Submitted from parent portal with invoice screenshot.',
    at: new Date('2026-02-12T10:22:00'),
  },
  {
    id: 'cmp-001-t2',
    complaintId: 'cmp-001',
    action: 'Assigned',
    actor: 'Education Division Admin',
    note: 'Routed to AR officer for subsidy verification.',
    at: new Date('2026-02-12T11:05:00'),
  },
  {
    id: 'cmp-001-t3',
    complaintId: 'cmp-001',
    action: 'Investigation Update',
    actor: 'Finance Officer (AR)',
    note: 'Fee rule and subsidy mapping under review for centre WM001.',
    at: new Date('2026-02-13T09:40:00'),
  },
  {
    id: 'cmp-002-t1',
    complaintId: 'cmp-002',
    action: 'Resolved',
    actor: 'Centre Admin',
    note: 'Face ID device sync retried. Attendance entry restored.',
    at: new Date('2026-02-13T14:30:00'),
  },
];
