import type { EducationLevel } from '../types';

export interface Institute {
  id: string;
  name: string;
  code: string;
  address: string;
  city: string;
  state: string;
  capacity: number;
  students: number;
  status: 'active' | 'inactive';
  educationLevel: EducationLevel;
  type: string;
  established?: string;
  phone?: string;
}

export const malaysianInstitutes: Institute[] = [

  // ── PRESCHOOL — Tadika Islam MAIWP (sample of 78 nationwide) ───────────
  {
    id: 'ti-001',
    name: 'Tadika Islam MAIWP Taman Tun Dr. Ismail',
    code: 'TI-MAIWP-001',
    address: 'No. 5 Jalan Datuk Sulaiman, Taman Tun Dr. Ismail',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 40,
    students: 32,
    status: 'active',
    educationLevel: 'preschool',
    type: 'MAIWP Kids (TMK)',
    established: '2022',
    phone: '03-7726 1234',
  },
  {
    id: 'ti-002',
    name: 'Tadika Islam MAIWP Cheras',
    code: 'TI-MAIWP-002',
    address: 'No. 12 Jalan Pandan Mewah, Pandan Mewah',
    city: 'Cheras',
    state: 'Wilayah Persekutuan',
    capacity: 50,
    students: 44,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Islam',
    established: '2009',
    phone: '03-9172 3456',
  },
  {
    id: 'ti-003',
    name: 'Tadika Islam MAIWP Wangsa Maju',
    code: 'TI-MAIWP-003',
    address: 'No. 7 Jalan 2/27A, Seksyen 2 Wangsa Maju',
    city: 'Wangsa Maju',
    state: 'Wilayah Persekutuan',
    capacity: 45,
    students: 38,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Islam',
    established: '2009',
    phone: '03-4142 5678',
  },
  {
    id: 'ti-004',
    name: 'Tadika Islam MAIWP Keramat',
    code: 'TI-MAIWP-004',
    address: 'Jalan Keramat Hujung, Off Jalan Keramat',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 40,
    students: 30,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Islam',
    established: '2009',
    phone: '03-4251 2345',
  },
  {
    id: 'ti-005',
    name: 'Tadika Islam MAIWP Sentul',
    code: 'TI-MAIWP-005',
    address: 'Jalan Sentul Pasar, Sentul',
    city: 'Sentul',
    state: 'Wilayah Persekutuan',
    capacity: 35,
    students: 27,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Islam',
    established: '2009',
    phone: '03-4041 3456',
  },
  {
    id: 'ti-006',
    name: 'Tadika Islam MAIWP Bangsar',
    code: 'TI-MAIWP-006',
    address: 'Jalan Telawi 3, Bangsar',
    city: 'Bangsar',
    state: 'Wilayah Persekutuan',
    capacity: 40,
    students: 35,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Permata MAIWP (TPM)',
    established: '2018',
    phone: '03-2282 4567',
  },
  {
    id: 'ti-007',
    name: 'Tadika Islam MAIWP Titiwangsa',
    code: 'TI-MAIWP-007',
    address: 'Jalan Pahang, Titiwangsa',
    city: 'Titiwangsa',
    state: 'Wilayah Persekutuan',
    capacity: 45,
    students: 39,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Islam',
    established: '2009',
    phone: '03-4023 5678',
  },
  {
    id: 'ti-008',
    name: 'Tadika Islam MAIWP Labuan',
    code: 'TI-MAIWP-L001',
    address: 'Jalan Wawasan 2, Bandar Labuan',
    city: 'Labuan',
    state: 'Wilayah Persekutuan Labuan',
    capacity: 30,
    students: 23,
    status: 'active',
    educationLevel: 'preschool',
    type: 'Tadika Islam',
    established: '2009',
    phone: '087-417 890',
  },

  // ── PRIMARY — Sekolah Agama Bantuan Kerajaan (SABK) ────────────────────
  {
    id: 'sabk-001',
    name: 'Sekolah Agama Bantuan Kerajaan Darul Ulum',
    code: 'SABK-WP-001',
    address: 'Jalan Raja Laut, Brickfields',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 200,
    students: 45,
    status: 'active',
    educationLevel: 'primary',
    type: 'SABK',
    established: '1985',
    phone: '03-2274 1234',
  },
  {
    id: 'sabk-002',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Amin',
    code: 'SABK-WP-002',
    address: 'Jalan Masjid India, Chow Kit',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 220,
    students: 52,
    status: 'active',
    educationLevel: 'primary',
    type: 'SABK',
    established: '1988',
    phone: '03-2692 2345',
  },
  {
    id: 'sabk-003',
    name: 'Sekolah Agama Bantuan Kerajaan Nurul Hidayah',
    code: 'SABK-WP-003',
    address: 'Jalan Cheras Batu 4½',
    city: 'Cheras',
    state: 'Wilayah Persekutuan',
    capacity: 180,
    students: 48,
    status: 'active',
    educationLevel: 'primary',
    type: 'SABK',
    established: '1990',
    phone: '03-9173 3456',
  },
  {
    id: 'srai-001',
    name: 'Sekolah Rendah Agama Integrasi Al-Falah',
    code: 'SRAI-WP-001',
    address: 'Jalan Sentul Pasar, Sentul',
    city: 'Sentul',
    state: 'Wilayah Persekutuan',
    capacity: 150,
    students: 38,
    status: 'active',
    educationLevel: 'primary',
    type: 'SRAI',
    established: '1995',
    phone: '03-4041 4567',
  },
  {
    id: 'srai-002',
    name: 'Sekolah Rendah Agama Integrasi Darul Ihsan',
    code: 'SRAI-WP-002',
    address: 'Jalan 2/27A, Seksyen 2 Wangsa Maju',
    city: 'Wangsa Maju',
    state: 'Wilayah Persekutuan',
    capacity: 160,
    students: 32,
    status: 'active',
    educationLevel: 'primary',
    type: 'SRAI',
    established: '1997',
    phone: '03-4142 6789',
  },

  // ── SECONDARY — Sekolah Menengah Agama MAIWP (real institutions) ────────
  {
    id: 'sma-kl',
    name: 'Sekolah Menengah Agama MAIWP Kuala Lumpur',
    code: 'SMA-MAIWP-KL',
    address: 'No. 2 Jalan Sri Permaisuri, Bandar Sri Permaisuri',
    city: 'Cheras',
    state: 'Wilayah Persekutuan',
    capacity: 300,
    students: 62,
    status: 'active',
    educationLevel: 'secondary',
    type: 'SMA (SABK)',
    established: '2007',
    phone: '03-9171 3661',
  },
  {
    id: 'sma-lbn',
    name: 'Sekolah Menengah Agama MAIWP Labuan',
    code: 'SMA-MAIWP-LBN',
    address: 'Jalan Bunga Tanjung, Bandar Labuan',
    city: 'Labuan',
    state: 'Wilayah Persekutuan Labuan',
    capacity: 200,
    students: 48,
    status: 'active',
    educationLevel: 'secondary',
    type: 'SMA (SABK)',
    established: '2010',
    phone: '087-413 456',
  },
  {
    id: 'smista',
    name: 'Sekolah Menengah Integrasi Sains Tahfiz',
    code: 'SMISTA-MAIWP',
    address: 'D/A Masjid Saidina Othman Ibn Affan, Jalan Budiman',
    city: 'Cheras',
    state: 'Wilayah Persekutuan',
    capacity: 250,
    students: 79,
    status: 'active',
    educationLevel: 'secondary',
    type: 'SMISTA (SABK)',
    established: '2011',
    phone: '03-9171 1005',
  },

  // ── UNIVERSITY / HIGHER EDUCATION — MAIWP institutions (real) ──────────
  {
    id: 'kpmaiwp',
    name: 'Kolej Profesional MAIWP',
    code: 'KPMAIWP',
    address: 'Lot 1363 Jalan Perkasa Maluri',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 600,
    students: 180,
    status: 'active',
    educationLevel: 'university',
    type: 'Kolej Profesional',
    established: '1992',
    phone: '03-9283 6789',
  },
  {
    id: 'ikb',
    name: 'Institut Kemahiran Baitulmal',
    code: 'IKB-MAIWP',
    address: 'Lot 1363, Jalan Perkasa, Off Jalan Kampung Pandan, Taman Maluri',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 300,
    students: 132,
    status: 'active',
    educationLevel: 'university',
    type: 'Institut Kemahiran',
    established: '1991',
    phone: '03-9283 0198',
  },
];
