import type { StudentApplication, TransferRequest, WithdrawalRequest, TimelineEvent } from '../types/student-lifecycle';

// ============================================================
// MOCK APPLICATIONS
// ============================================================

export const mockApplications: StudentApplication[] = [
  {
    id: 'app-001',
    studentName: 'Zahra binti Mohd Faisal',
    ic: '190825-14-0099',
    dateOfBirth: new Date('2019-08-25'),
    guardianName: 'Mohd Faisal bin Yusof',
    guardianPhone: '+60123990011',
    guardianEmail: 'faisal.yusof@gmail.com',
    centreId: 'ti-001',
    centreName: 'Tadika Islam MAIWP Taman Tun Dr. Ismail',
    educationLevel: 'preschool',
    subsidyCategory: 'B40',
    status: 'submitted',
    appliedDate: new Date('2024-03-01'),
    notes: 'Adik kepada pelajar sedia ada TI-2024-001',
  },
  {
    id: 'app-002',
    studentName: 'Adam Irfan bin Rizal',
    ic: '180412-14-0088',
    dateOfBirth: new Date('2018-04-12'),
    guardianName: 'Rizal bin Hamdan',
    guardianPhone: '+60198877001',
    guardianEmail: 'rizal.hamdan@email.com',
    centreId: 'ti-002',
    centreName: 'Tadika Islam MAIWP Cheras',
    educationLevel: 'preschool',
    subsidyCategory: 'M40',
    status: 'approved',
    appliedDate: new Date('2024-02-15'),
    reviewedDate: new Date('2024-02-20'),
    reviewedBy: 'Pn. Rozita binti Hamid',
    notes: 'Dokumen lengkap, lulus semakan',
  },
  {
    id: 'app-003',
    studentName: 'Nur Batrisyia binti Azman',
    ic: '120803-14-0077',
    dateOfBirth: new Date('2012-08-03'),
    guardianName: 'Azman bin Kassim',
    guardianPhone: '+60167788223',
    guardianEmail: 'azman.kassim@yahoo.com',
    centreId: 'sabk-001',
    centreName: 'SABK Darul Ulum',
    educationLevel: 'primary',
    subsidyCategory: 'Asnaf',
    status: 'under_review',
    appliedDate: new Date('2024-03-10'),
    notes: 'Menunggu pengesahan dokumen Asnaf dari Baitulmal',
  },
  {
    id: 'app-004',
    studentName: 'Muhammad Haziq bin Roslan',
    ic: '110215-14-0066',
    dateOfBirth: new Date('2011-02-15'),
    guardianName: 'Roslan bin Talib',
    guardianPhone: '+60145566778',
    guardianEmail: 'roslan.talib@gmail.com',
    centreId: 'sabk-002',
    centreName: 'SABK Al-Amin',
    educationLevel: 'primary',
    subsidyCategory: 'B40',
    status: 'enrolled',
    appliedDate: new Date('2024-01-05'),
    reviewedDate: new Date('2024-01-10'),
    reviewedBy: 'Ust. Zulkifli bin Ahmad',
  },
  {
    id: 'app-005',
    studentName: 'Aisyah Humaira binti Shahrul',
    ic: '080930-14-0055',
    dateOfBirth: new Date('2008-09-30'),
    guardianName: 'Shahrul bin Nizam',
    guardianPhone: '+60133344556',
    guardianEmail: 'shahrul.nizam@email.com',
    centreId: 'sma-kl',
    centreName: 'SMA MAIWP Kuala Lumpur',
    educationLevel: 'secondary',
    subsidyCategory: 'M40',
    status: 'rejected',
    appliedDate: new Date('2024-02-01'),
    reviewedDate: new Date('2024-02-10'),
    reviewedBy: 'Ust. Siti Aishah binti Mahmud',
    notes: 'Kapasiti penuh untuk sesi 2024. Dicadangkan permohonan semula sesi 2025.',
  },
  {
    id: 'app-006',
    studentName: 'Luqman Hakim bin Faizal',
    ic: '050714-14-0044',
    dateOfBirth: new Date('2005-07-14'),
    guardianName: 'Faizal bin Osman',
    guardianPhone: '+60112233445',
    guardianEmail: 'faizal.osman@gmail.com',
    centreId: 'kpmaiwp',
    centreName: 'Kolej Profesional MAIWP',
    educationLevel: 'university',
    subsidyCategory: 'B40',
    status: 'submitted',
    appliedDate: new Date('2024-03-15'),
    notes: 'Permohonan Diploma Teknologi Maklumat',
  },
  {
    id: 'app-007',
    studentName: 'Siti Mariam binti Kamal',
    ic: '190105-14-0033',
    dateOfBirth: new Date('2019-01-05'),
    guardianName: 'Kamal bin Sulaiman',
    guardianPhone: '+60199988776',
    guardianEmail: 'kamal.sulaiman@email.com',
    centreId: 'ti-003',
    centreName: 'Tadika Islam MAIWP Wangsa Maju',
    educationLevel: 'preschool',
    subsidyCategory: 'T20',
    status: 'draft',
    appliedDate: new Date('2024-03-20'),
  },
  {
    id: 'app-008',
    studentName: 'Imran bin Hafiz',
    ic: '060328-14-0022',
    dateOfBirth: new Date('2006-03-28'),
    guardianName: 'Hafiz bin Razak',
    guardianPhone: '+60177766554',
    guardianEmail: 'hafiz.razak@yahoo.com',
    centreId: 'ikb',
    centreName: 'Institut Kemahiran Baitulmal',
    educationLevel: 'university',
    subsidyCategory: 'Asnaf',
    status: 'approved',
    appliedDate: new Date('2024-02-28'),
    reviewedDate: new Date('2024-03-05'),
    reviewedBy: 'En. Rashdan bin Muiz',
    notes: 'Permohonan Sijil Kemahiran Automotif. Disahkan status Asnaf.',
  },
];

// ============================================================
// MOCK TRANSFER REQUESTS
// ============================================================

export const mockTransferRequests: TransferRequest[] = [
  {
    id: 'tr-001',
    studentId: 'ps-003',
    studentName: 'Hana Sofea binti Khairul',
    fromCentreId: 'ti-001',
    fromCentreName: 'Tadika Islam MAIWP Taman Tun Dr. Ismail',
    toCentreId: 'ti-002',
    toCentreName: 'Tadika Islam MAIWP Cheras',
    reason: 'Keluarga berpindah ke Cheras',
    status: 'completed',
    requestedDate: new Date('2024-02-01'),
    completedDate: new Date('2024-02-15'),
    processedBy: 'Pn. Norazura binti Kassim',
    educationLevel: 'preschool',
  },
  {
    id: 'tr-002',
    studentId: 'pr-005',
    studentName: 'Muhammad Aiman bin Zulkifli',
    fromCentreId: 'sabk-001',
    fromCentreName: 'SABK Darul Ulum',
    toCentreId: 'sabk-003',
    toCentreName: 'SABK Nurul Hidayah',
    reason: 'Lebih dekat dengan rumah baharu',
    status: 'requested',
    requestedDate: new Date('2024-03-10'),
    educationLevel: 'primary',
  },
  {
    id: 'tr-003',
    studentId: 'sc-002',
    studentName: 'Nurul Izzah binti Kamaruddin',
    fromCentreId: 'sma-kl',
    fromCentreName: 'SMA MAIWP Kuala Lumpur',
    toCentreId: 'sma-lbn',
    toCentreName: 'SMA MAIWP Labuan',
    reason: 'Ibu bapa bertugas di Labuan',
    status: 'approved',
    requestedDate: new Date('2024-03-01'),
    processedBy: 'Ust. Siti Aishah binti Mahmud',
    educationLevel: 'secondary',
  },
  {
    id: 'tr-004',
    studentId: 'pr-008',
    studentName: 'Fatimah Zahrah binti Hamdan',
    fromCentreId: 'sabk-002',
    fromCentreName: 'SABK Al-Amin',
    toCentreId: 'srai-001',
    toCentreName: 'SRAI Al-Falah',
    reason: 'Ingin bertukar ke aliran agama rakyat',
    status: 'cancelled',
    requestedDate: new Date('2024-01-20'),
    processedBy: 'Ust. Zulkifli bin Ahmad',
    educationLevel: 'primary',
  },
];

// ============================================================
// MOCK WITHDRAWAL REQUESTS
// ============================================================

export const mockWithdrawalRequests: WithdrawalRequest[] = [
  {
    id: 'wd-001',
    studentId: 'ps-008',
    studentName: 'Puteri Nur Alya binti Ramzi',
    centreId: 'ti-003',
    centreName: 'Tadika Islam MAIWP Wangsa Maju',
    reason: 'Keluarga berpindah ke Johor Bahru',
    lastDay: new Date('2024-03-31'),
    status: 'completed',
    requestedDate: new Date('2024-03-01'),
    completedDate: new Date('2024-03-15'),
    processedBy: 'Pn. Hasanah binti Yusof',
    refundAmount: 50,
    educationLevel: 'preschool',
  },
  {
    id: 'wd-002',
    studentId: 'pr-010',
    studentName: 'Ahmad Luqman bin Azhari',
    centreId: 'sabk-001',
    centreName: 'SABK Darul Ulum',
    reason: 'Bertukar ke sekolah kebangsaan',
    lastDay: new Date('2024-04-30'),
    status: 'requested',
    requestedDate: new Date('2024-03-20'),
    refundAmount: 200,
    educationLevel: 'primary',
  },
  {
    id: 'wd-003',
    studentId: 'un-003',
    studentName: 'Amirul Hakim bin Nazri',
    centreId: 'kpmaiwp',
    centreName: 'Kolej Profesional MAIWP',
    reason: 'Mendapat tawaran universiti awam',
    lastDay: new Date('2024-02-28'),
    status: 'completed',
    requestedDate: new Date('2024-02-01'),
    completedDate: new Date('2024-02-20'),
    processedBy: 'Dr. Mohd Aizuddin bin Aziz',
    refundAmount: 500,
    educationLevel: 'university',
  },
];

// ============================================================
// MOCK TIMELINE EVENTS
// ============================================================

export const mockTimelineEvents: TimelineEvent[] = [
  // Student ps-001
  {
    id: 'tl-001', studentId: 'ps-001', type: 'application',
    title: 'Permohonan Diterima',
    description: 'Permohonan pendaftaran diterima untuk Tadika Islam MAIWP TTDI',
    date: new Date('2023-12-01'), performedBy: 'System',
  },
  {
    id: 'tl-002', studentId: 'ps-001', type: 'registration',
    title: 'Pendaftaran Berjaya',
    description: 'Pelajar didaftarkan secara rasmi. Kod pelajar: TI-2024-001',
    date: new Date('2024-01-08'), performedBy: 'Pn. Norazura binti Kassim',
  },
  {
    id: 'tl-003', studentId: 'ps-001', type: 'fee_change',
    title: 'Yuran Bulanan Ditetapkan',
    description: 'Yuran bulanan: RM 150.00. Subsidi B40 (80%): RM 120.00. Baki bayar: RM 30.00',
    date: new Date('2024-01-08'), performedBy: 'System',
  },
  {
    id: 'tl-004', studentId: 'ps-001', type: 'note',
    title: 'Catatan Guru',
    description: 'Pelajar menyesuaikan diri dengan baik. Aktif dalam kelas.',
    date: new Date('2024-02-15'), performedBy: 'Pn. Norazura binti Kassim',
  },

  // Student pr-001
  {
    id: 'tl-005', studentId: 'pr-001', type: 'application',
    title: 'Application Received',
    description: 'Application for SABK Darul Ulum received',
    date: new Date('2023-11-15'), performedBy: 'System',
  },
  {
    id: 'tl-006', studentId: 'pr-001', type: 'registration',
    title: 'Student Registered',
    description: 'Officially registered. Student code: SABK-2024-001',
    date: new Date('2024-01-02'), performedBy: 'Ust. Mohd Nor bin Khalid',
  },
  {
    id: 'tl-007', studentId: 'pr-001', type: 'status_change',
    title: 'Status Updated',
    description: 'Status changed from Pending to Active',
    date: new Date('2024-01-02'), performedBy: 'Ust. Mohd Nor bin Khalid',
  },

  // Student sc-001
  {
    id: 'tl-008', studentId: 'sc-001', type: 'registration',
    title: 'Student Registered',
    description: 'Registered at SMA MAIWP Kuala Lumpur. Student code: SMA-2024-001',
    date: new Date('2024-01-03'), performedBy: 'Ust. Siti Aishah binti Mahmud',
  },
  {
    id: 'tl-009', studentId: 'sc-001', type: 'fee_change',
    title: 'Monthly Fee Set',
    description: 'Monthly fee: RM 300.00. M40 subsidy (50%): RM 150.00. Net: RM 150.00',
    date: new Date('2024-01-03'), performedBy: 'System',
  },

  // Student ps-003 (transferred)
  {
    id: 'tl-010', studentId: 'ps-003', type: 'registration',
    title: 'Student Registered',
    description: 'Registered at Tadika Islam MAIWP TTDI',
    date: new Date('2024-01-12'), performedBy: 'Pn. Norazura binti Kassim',
  },
  {
    id: 'tl-011', studentId: 'ps-003', type: 'transfer',
    title: 'Transfer Requested',
    description: 'Transfer requested from TTDI to Cheras branch. Reason: Family relocation.',
    date: new Date('2024-02-01'), performedBy: 'Pn. Norazura binti Kassim',
  },
  {
    id: 'tl-012', studentId: 'ps-003', type: 'transfer',
    title: 'Transfer Completed',
    description: 'Successfully transferred to Tadika Islam MAIWP Cheras',
    date: new Date('2024-02-15'), performedBy: 'Pn. Rozita binti Hamid',
  },

  // Student ps-008 (withdrawn)
  {
    id: 'tl-013', studentId: 'ps-008', type: 'registration',
    title: 'Student Registered',
    description: 'Registered at Tadika Islam MAIWP Wangsa Maju',
    date: new Date('2024-01-15'), performedBy: 'Pn. Hasanah binti Yusof',
  },
  {
    id: 'tl-014', studentId: 'ps-008', type: 'withdrawal',
    title: 'Withdrawal Requested',
    description: 'Withdrawal requested. Reason: Family relocating to Johor Bahru.',
    date: new Date('2024-03-01'), performedBy: 'System',
  },
  {
    id: 'tl-015', studentId: 'ps-008', type: 'withdrawal',
    title: 'Withdrawal Completed',
    description: 'Student withdrawn. Deposit refund: RM 50.00 processed.',
    date: new Date('2024-03-15'), performedBy: 'Pn. Hasanah binti Yusof',
  },

  // Student un-001
  {
    id: 'tl-016', studentId: 'un-001', type: 'registration',
    title: 'Student Enrolled',
    description: 'Enrolled in Diploma Teknologi Maklumat at Kolej Profesional MAIWP',
    date: new Date('2024-01-10'), performedBy: 'Dr. Mohd Aizuddin bin Aziz',
  },
  {
    id: 'tl-017', studentId: 'un-001', type: 'fee_change',
    title: 'Semester Fee Set',
    description: 'Semester fee: RM 2,500.00. Asnaf subsidy (100%): RM 2,500.00. Net: RM 0.00',
    date: new Date('2024-01-10'), performedBy: 'System',
  },

  // Reenrollment example
  {
    id: 'tl-018', studentId: 'un-003', type: 'withdrawal',
    title: 'Student Withdrawn',
    description: 'Withdrawn from Kolej Profesional MAIWP. Reason: Accepted at public university.',
    date: new Date('2024-02-20'), performedBy: 'Dr. Mohd Aizuddin bin Aziz',
  },
  {
    id: 'tl-019', studentId: 'un-003', type: 'reenrollment',
    title: 'Re-enrollment Inquiry',
    description: 'Guardian inquired about re-enrollment for next semester.',
    date: new Date('2024-03-15'), performedBy: 'System',
  },
];
