'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';

export default function NewComplaintPage() {
  const [submitted, setSubmitted] = useState(false);

  return (
    <div className="space-y-6 max-w-3xl">
      <div className="space-y-3">
        <Link href="/admin/complaints" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-4 w-4" /> Back to complaints
        </Link>
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Register New Complaint</h1>
          <p className="text-muted-foreground">Capture complaint details for triage and SLA routing.</p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Complaint Form</CardTitle>
          <CardDescription>Demo form for UI workflow. Submission does not persist yet.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Student Name</Label>
              <Input placeholder="e.g., Ahmad Bin Abdullah" />
            </div>
            <div className="space-y-2">
              <Label>Centre</Label>
              <Input placeholder="e.g., Pusat Jagaan Wangsa Maju" />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label>Category</Label>
              <Select>
                <SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="billing">Billing</SelectItem>
                  <SelectItem value="attendance">Attendance</SelectItem>
                  <SelectItem value="behaviour">Behaviour</SelectItem>
                  <SelectItem value="facility">Facility</SelectItem>
                  <SelectItem value="staff">Staff</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Priority</Label>
              <Select>
                <SelectTrigger><SelectValue placeholder="Select priority" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Low</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="critical">Critical</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Channel</Label>
              <Select>
                <SelectTrigger><SelectValue placeholder="Select channel" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="portal">Portal</SelectItem>
                  <SelectItem value="whatsapp">WhatsApp</SelectItem>
                  <SelectItem value="email">Email</SelectItem>
                  <SelectItem value="walk_in">Walk-in</SelectItem>
                  <SelectItem value="phone">Phone</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Subject</Label>
            <Input placeholder="Short title of the complaint" />
          </div>

          <div className="space-y-2">
            <Label>Description</Label>
            <Textarea placeholder="Enter detailed complaint information and supporting context" className="min-h-32" />
          </div>

          <div className="flex justify-end gap-2">
            <Link href="/admin/complaints"><Button variant="outline">Cancel</Button></Link>
            <Button onClick={() => setSubmitted(true)}>Submit Complaint</Button>
          </div>

          {submitted && (
            <p className="text-sm text-green-700 bg-green-50 border border-green-200 rounded-md px-3 py-2">
              Complaint submitted in demo mode. Reference would be generated by workflow engine.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
